version: "3.8"

services:
  chat-server:
    image: drlivesey23/chat-server:latest
    container_name: chat-server
    ports:
      - "8000:8000"
    environment:
      MONGO_DETAILS: "mongodb+srv://admin:28052002@alaeddineapi.kxaujo9.mongodb.net/test-store?retryWrites=true&w=majority"

  react-client:
    image: drlivesey23/logan_summer_project_1_vite_client:latest
    container_name: react-client
    environment:
      - VITE_REACT_APP_API_URL=localhost:5000/api
    ports:
      - "192.168.1.145:30001:9999"

  node-server:
    image: drlivesey23/logan_summer_project_1_server:latest
    container_name: node-server
    ports:
      - "5000:5000"
    environment:
      MONGO_DETAILS: "mongodb+srv://admin:28052002@alaeddineapi.kxaujo9.mongodb.net/test-store?retryWrites=true&w=majority"
