version: "3.8"

services:
  chat-server:
    build:
      context: ./chat-server
    container_name: chat-server
    ports:
      - "8000:8000"
    environment:
      MONGO_DETAILS: "mongodb+srv://admin:28052002@alaeddineapi.kxaujo9.mongodb.net/test-store?retryWrites=true&w=majority"

  react-client:
    build:
      context: ./client
    container_name: react-client
    ports:
      - "3000:80"

  node-server:
    build:
      context: ./server
    container_name: node-server
    ports:
      - "5000:5000"
    environment:
      MONGO_DETAILS: "mongodb+srv://admin:28052002@alaeddineapi.kxaujo9.mongodb.net/test-store?retryWrites=true&w=majority"
