FROM node:22-alpine AS build

WORKDIR /server

RUN apk upgrade --update-cache --available \
    && apk add openssl

COPY ./certs/openssl.cnf /etc/ssl/openssl.cnf

COPY package.json ./
COPY package-lock.json ./

RUN npm install

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./selfsigned.key -out selfsigned.crt

COPY . .

EXPOSE 5000

CMD ["node", "server.js"]
